service: cors-proxy

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 60
  stage: ${opt:stage}
  region: us-east-1

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
